export const SYMBOLS_SERIES = {
  SERIE_REPOSITORY: Symbol('SERIE_REPOSITORY'),
  LIST_SERIES: Symbol('LIST_SERIES'),
  LIST_SERIE_BY_ID: Symbol('LIST_SERIE_BY_ID'),
  LIST_RESOURCES_BY_SERIE_ID_AND_RESOURCE_NAME: Symbol(
    'LIST_RESOURCES_BY_SERIE_ID_AND_RESOURCE_NAME'
  )
}
